repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c "PYTHONPATH=. poetry run pytest"
        language: system
        types: [python]
        pass_filenames: false
        always_run: true 
        verbose: true
